# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NGet NuGet Packages

on:
  push:
    branches: [ "master" ]

jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]
        
    runs-on: windows-2019

    steps:
    - name: Publish NGet NuGet Package
      uses: brandedoutcast/publish-nuget@master
      with:
        repository: NGen/NGen.csproj
        token: ${{secrets.NUGET_KEY}}


    # - name: Publish NGen.Website NuGet Package
    #   uses: actions/checkout@master
    #   with:
    #     PROJECT_FILE_PATH: NGen.Website/NGen.Website.csproj
    #     NUGET_KEY: ${{secrets.NUGET_KEY}}
        

    # - name: Publish NGen.FileManager NuGet Package
    #   uses: actions/checkout@master
    #   with:
    #     PROJECT_FILE_PATH: NGen.FileManager/NGen.FileManager.csproj
    #     NUGET_KEY: ${{secrets.NUGET_KEY}}
